apiVersion: apps/v1
kind: Deployment
metadata:
 annotations:
  deployment.kubernetes.io/revision: '1'
 labels:
  app: frontnedui
 name: frontnedui
 namespace: default
spec:
 replicas: 1
 selector:
  matchLabels:
   app: frontnedui
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 1
 template:
  metadata:
   labels:
    app: frontnedui
  spec:
   containers:
    - image: gremiumsoft/frontend-ui:latest
      imagePullPolicy: Always
      name: frontnedui
      resources:
        limits:
          memory: 128Mi
        requests:
          memory: 64Mi
      terminationMessagePath: "/dev/termination-log"
      terminationMessagePolicy: File
   dnsPolicy: ClusterFirst
   restartPolicy: Always
   schedulerName: default-scheduler
   securityContext: {}
   terminationGracePeriodSeconds: 30

